// Preloaded realistic demo datasets for instant visualization & testing

export const DEMO_PRESETS = {
  ecommerce: {
    name: "Fashion Hub (E-Commerce)",
    url: "https://shop.fashionhub.io",
    pages: [
      {
        url: "https://shop.fashionhub.io/",
        title: "FashionHub - Contemporary Clothing & Designer Apparel",
        description: "Discover the latest seasonal trends in menswear, womenswear, luxury accessories, and sustainable streetwear with free worldwide delivery.",
        h1: "Define Your Signature Style",
        statusCode: 200,
        loadTime: 240,
        sizeKb: 38,
        depth: 0,
        imagesCount: 14,
        hasCanonical: true,
        isIndexable: true,
        lastmod: "2026-03-01",
        changefreq: "daily",
        priority: 1.0,
      },
      {
        url: "https://shop.fashionhub.io/collections/women",
        title: "Women's Collection - Dresses, Coats & Footwear | FashionHub",
        description: "Explore chic dresses, tailored outerwear, denim, and footwear designed for modern comfort and effortless elegance.",
        h1: "Women's Collection 2026",
        statusCode: 200,
        loadTime: 310,
        sizeKb: 54,
        depth: 1,
        imagesCount: 22,
        hasCanonical: true,
        isIndexable: true,
        lastmod: "2026-03-02",
        changefreq: "daily",
        priority: 0.9,
      },
      {
        url: "https://shop.fashionhub.io/collections/men",
        title: "Men's Apparel - Suits, Casuals & Sneakers | FashionHub",
        description: "Shop premium menswear essentials, lightweight summer jackets, tailored trousers, and leather sneakers.",
        h1: "Men's New Arrivals",
        statusCode: 200,
        loadTime: 290,
        sizeKb: 48,
        depth: 1,
        imagesCount: 18,
        hasCanonical: true,
        isIndexable: true,
        lastmod: "2026-03-02",
        changefreq: "daily",
        priority: 0.9,
      },
      {
        url: "https://shop.fashionhub.io/collections/accessories",
        title: "Designer Accessories, Watches & Handbags | FashionHub",
        description: "Complete your outfit with handcrafted leather bags, minimal sunglasses, silk scarves, and chronographs.",
        h1: "Luxury Accessories",
        statusCode: 200,
        loadTime: 340,
        sizeKb: 42,
        depth: 1,
        imagesCount: 16,
        hasCanonical: true,
        isIndexable: true,
        lastmod: "2026-02-28",
        changefreq: "weekly",
        priority: 0.8,
      },
      {
        url: "https://shop.fashionhub.io/products/cashmere-sweater",
        title: "Italian Cashmere Crewneck Sweater - Sand Dune | FashionHub",
        description: "100% Mongolian pure cashmere sweater featuring ribbed trims and breathable knit construction.",
        h1: "Pure Cashmere Crewneck",
        statusCode: 200,
        loadTime: 420,
        sizeKb: 65,
        depth: 2,
        imagesCount: 8,
        hasCanonical: true,
        isIndexable: true,
        lastmod: "2026-02-25",
        changefreq: "weekly",
        priority: 0.7,
      },
      {
        url: "https://shop.fashionhub.io/products/leather-tote",
        title: "Artisanal Tuscan Leather Tote Bag - Obsidian | FashionHub",
        description: "Vegetable-tanned full-grain leather tote with reinforced brass hardware and laptop sleeve compartment.",
        h1: "Tuscan Leather Tote Bag",
        statusCode: 200,
        loadTime: 390,
        sizeKb: 72,
        depth: 2,
        imagesCount: 10,
        hasCanonical: true,
        isIndexable: true,
        lastmod: "2026-02-20",
        changefreq: "weekly",
        priority: 0.7,
      },
      {
        url: "https://shop.fashionhub.io/products/vintage-sunglasses",
        title: "Retro Polarized Acetate Sunglasses | FashionHub",
        description: "", // Missing description test case!
        h1: "Polarized Retro Sunglasses",
        statusCode: 200,
        loadTime: 280,
        sizeKb: 31,
        depth: 2,
        imagesCount: 6,
        hasCanonical: false, // Missing canonical test case
        isIndexable: true,
        lastmod: "2026-02-15",
        changefreq: "monthly",
        priority: 0.6,
      },
      {
        url: "https://shop.fashionhub.io/about",
        title: "Our Story - Sustainable Ethics & Craftsmanship | FashionHub",
        description: "Learn how we partner with zero-waste mills across Portugal and Italy to craft lifelong wardrobe essentials.",
        h1: "Crafted with Purpose",
        statusCode: 200,
        loadTime: 180,
        sizeKb: 24,
        depth: 1,
        imagesCount: 5,
        hasCanonical: true,
        isIndexable: true,
        lastmod: "2026-01-10",
        changefreq: "monthly",
        priority: 0.5,
      },
      {
        url: "https://shop.fashionhub.io/blog/summer-style-guide",
        title: "Summer 2026 Style Guide: Minimalist Layering and Earth Tones",
        description: "Expert styling advice on breathable linens, relaxed suiting silhouettes, and effortless capsule wardrobes for warm days.",
        h1: "Summer 2026 Style Guide",
        statusCode: 200,
        loadTime: 210,
        sizeKb: 45,
        depth: 2,
        imagesCount: 9,
        hasCanonical: true,
        isIndexable: true,
        lastmod: "2026-03-01",
        changefreq: "weekly",
        priority: 0.7,
      },
      {
        url: "https://shop.fashionhub.io/promotions/spring-sale-2024",
        title: "Old Sale", // Short title test case
        description: "Old spring promotion page.",
        h1: "", // Missing H1 test case
        statusCode: 404, // Broken page test case!
        loadTime: 820,
        sizeKb: 12,
        depth: 2,
        imagesCount: 0,
        hasCanonical: false,
        isIndexable: false,
        lastmod: "2024-04-12",
        changefreq: "never",
        priority: 0.2,
      },
      {
        url: "https://shop.fashionhub.io/contact",
        title: "Customer Concierge & Support - FashionHub",
        description: "Need help with sizing, worldwide tracking, or returns? Our styling concierge is online 24/7.",
        h1: "How Can We Help You?",
        statusCode: 200,
        loadTime: 195,
        sizeKb: 20,
        depth: 1,
        imagesCount: 2,
        hasCanonical: true,
        isIndexable: true,
        lastmod: "2026-01-01",
        changefreq: "monthly",
        priority: 0.4,
      }
    ]
  },
  saas: {
    name: "CloudScale AI (SaaS Platform)",
    url: "https://cloudscale.ai",
    pages: [
      {
        url: "https://cloudscale.ai/",
        title: "CloudScale AI - Autonomous Distributed GPU Infrastructure for LLMs",
        description: "Deploy, fine-tune, and orchestrate deep learning foundation models across global multi-cloud clusters with sub-millisecond routing.",
        h1: "Compute Infrastructure for the Next Wave of AI",
        statusCode: 200,
        loadTime: 190,
        sizeKb: 45,
        depth: 0,
        imagesCount: 12,
        hasCanonical: true,
        isIndexable: true,
        lastmod: "2026-03-05",
        changefreq: "daily",
        priority: 1.0,
      },
      {
        url: "https://cloudscale.ai/pricing",
        title: "Transparent Compute Pricing - On-Demand & Reserved Clusters | CloudScale",
        description: "Zero egress fees. Per-second GPU billing across H100, B200, and TPU nodes with enterprise SLAs.",
        h1: "Predictable, Scalable Pricing",
        statusCode: 200,
        loadTime: 230,
        sizeKb: 34,
        depth: 1,
        imagesCount: 4,
        hasCanonical: true,
        isIndexable: true,
        lastmod: "2026-03-04",
        changefreq: "weekly",
        priority: 0.9,
      },
      {
        url: "https://cloudscale.ai/docs",
        title: "Developer Documentation & API Reference | CloudScale AI",
        description: "Official guides, SDKs for Python and TypeScript, CLI commands, and cluster configuration schemas.",
        h1: "CloudScale Documentation",
        statusCode: 200,
        loadTime: 270,
        sizeKb: 52,
        depth: 1,
        imagesCount: 6,
        hasCanonical: true,
        isIndexable: true,
        lastmod: "2026-03-06",
        changefreq: "daily",
        priority: 0.9,
      },
      {
        url: "https://cloudscale.ai/docs/quickstart",
        title: "Quickstart: Deploy Your First Model in 60 Seconds",
        description: "Learn how to authenticate with your API token and spin up a distributed inference endpoint via the CloudScale CLI.",
        h1: "Quickstart Guide",
        statusCode: 200,
        loadTime: 310,
        sizeKb: 48,
        depth: 2,
        imagesCount: 5,
        hasCanonical: true,
        isIndexable: true,
        lastmod: "2026-03-03",
        changefreq: "weekly",
        priority: 0.8,
      },
      {
        url: "https://cloudscale.ai/features/distributed-training",
        title: "Distributed Training with Zero-Redundancy Optimizer | CloudScale",
        description: "Seamlessly shard billion-parameter checkpoints across heterogeneous clusters with automated failure recovery.",
        h1: "Distributed Training Engine",
        statusCode: 200,
        loadTime: 280,
        sizeKb: 61,
        depth: 2,
        imagesCount: 8,
        hasCanonical: true,
        isIndexable: true,
        lastmod: "2026-02-28",
        changefreq: "monthly",
        priority: 0.8,
      },
      {
        url: "https://cloudscale.ai/features/inference-gateway",
        title: "Low-Latency Global Inference Gateway | CloudScale",
        description: "Edge caching, speculative decoding, and automatic quantization for mission-critical production workloads.",
        h1: "Global Inference Engine",
        statusCode: 200,
        loadTime: 260,
        sizeKb: 41,
        depth: 2,
        imagesCount: 7,
        hasCanonical: true,
        isIndexable: true,
        lastmod: "2026-02-26",
        changefreq: "monthly",
        priority: 0.8,
      },
      {
        url: "https://cloudscale.ai/changelog",
        title: "Changelog & Product Releases - CloudScale",
        description: "Explore all recent infrastructure updates, performance enhancements, and security patches.",
        h1: "Product Changelog",
        statusCode: 200,
        loadTime: 350,
        sizeKb: 55,
        depth: 1,
        imagesCount: 4,
        hasCanonical: true,
        isIndexable: true,
        lastmod: "2026-03-05",
        changefreq: "weekly",
        priority: 0.7,
      },
      {
        url: "https://cloudscale.ai/security",
        title: "Enterprise Security, SOC2 & HIPAA Compliance | CloudScale",
        description: "End-to-end data encryption at rest and in transit, isolated tenant VPCs, and compliance certifications.",
        h1: "Enterprise-Grade Security",
        statusCode: 200,
        loadTime: 210,
        sizeKb: 38,
        depth: 1,
        imagesCount: 3,
        hasCanonical: true,
        isIndexable: true,
        lastmod: "2026-01-20",
        changefreq: "monthly",
        priority: 0.6,
      }
    ]
  },
  blog: {
    name: "DevVelocity (Tech Blog)",
    url: "https://devvelocity.dev",
    pages: [
      {
        url: "https://devvelocity.dev/",
        title: "DevVelocity - Modern Fullstack Engineering & System Architecture",
        description: "Deep dive articles, architectural design patterns, React performance benchmarks, and distributed database tutorials.",
        h1: "High Velocity Software Engineering",
        statusCode: 200,
        loadTime: 160,
        sizeKb: 28,
        depth: 0,
        imagesCount: 8,
        hasCanonical: true,
        isIndexable: true,
        lastmod: "2026-03-07",
        changefreq: "daily",
        priority: 1.0,
      },
      {
        url: "https://devvelocity.dev/posts/mastering-react-19-compiler",
        title: "Mastering the React 19 Compiler: Goodbye useMemo and useCallback",
        description: "An in-depth investigation into automatic memoization, compilation pipeline mechanics, and real-world bundle size reductions.",
        h1: "Mastering the React 19 Compiler",
        statusCode: 200,
        loadTime: 220,
        sizeKb: 64,
        depth: 2,
        imagesCount: 7,
        hasCanonical: true,
        isIndexable: true,
        lastmod: "2026-03-04",
        changefreq: "monthly",
        priority: 0.8,
      },
      {
        url: "https://devvelocity.dev/posts/building-distributed-event-streams",
        title: "Building Resilient Distributed Event Streams in Rust",
        description: "How to engineer a sub-millisecond append-only log with raft consensus, memory-mapped files, and zero-copy deserialization.",
        h1: "Distributed Event Streams in Rust",
        statusCode: 200,
        loadTime: 240,
        sizeKb: 72,
        depth: 2,
        imagesCount: 5,
        hasCanonical: true,
        isIndexable: true,
        lastmod: "2026-02-22",
        changefreq: "monthly",
        priority: 0.8,
      },
      {
        url: "https://devvelocity.dev/categories/frontend",
        title: "Frontend Engineering Articles & Guides - DevVelocity",
        description: "Curated collection of guides covering modern CSS, Web Components, Vite optimizations, and state management.",
        h1: "Frontend Engineering",
        statusCode: 200,
        loadTime: 180,
        sizeKb: 36,
        depth: 1,
        imagesCount: 6,
        hasCanonical: true,
        isIndexable: true,
        lastmod: "2026-03-01",
        changefreq: "weekly",
        priority: 0.7,
      },
      {
        url: "https://devvelocity.dev/categories/backend",
        title: "Backend & Systems Architecture - DevVelocity",
        description: "Articles exploring Postgres query planning, microservices, gRPC, and cloud native Kubernetes deployment.",
        h1: "Backend & Distributed Systems",
        statusCode: 200,
        loadTime: 175,
        sizeKb: 35,
        depth: 1,
        imagesCount: 6,
        hasCanonical: true,
        isIndexable: true,
        lastmod: "2026-02-28",
        changefreq: "weekly",
        priority: 0.7,
      },
      {
        url: "https://devvelocity.dev/about",
        title: "About the Authors & Publication - DevVelocity",
        description: "Meet the distributed systems engineers and frontend leads contributing technical deep dives to DevVelocity.",
        h1: "About DevVelocity",
        statusCode: 200,
        loadTime: 150,
        sizeKb: 22,
        depth: 1,
        imagesCount: 4,
        hasCanonical: true,
        isIndexable: true,
        lastmod: "2026-01-05",
        changefreq: "monthly",
        priority: 0.5,
      }
    ]
  }
};
