// Client-side XML Sitemap, Robots.txt, and CSV Generator

export function generateSitemapXml(pages, options = {}) {
  const includeImages = options.includeImages !== false;

  let xml = '<?xml version="1.0" encoding="UTF-8"?>\n';
  xml += '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"';
  
  if (includeImages) {
    xml += '\n        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"';
  }
  xml += '>\n';

  pages.forEach(page => {
    // Only include successful pages in sitemap (2xx) or as configured
    if (page.statusCode && page.statusCode >= 400) return;

    xml += '  <url>\n';
    xml += `    <loc>${escapeXml(page.url)}</loc>\n`;
    
    if (page.lastmod) {
      xml += `    <lastmod>${page.lastmod}</lastmod>\n`;
    }
    
    if (page.changefreq) {
      xml += `    <changefreq>${page.changefreq}</changefreq>\n`;
    }
    
    if (page.priority !== undefined) {
      xml += `    <priority>${Number(page.priority).toFixed(1)}</priority>\n`;
    }

    if (includeImages && page.imagesCount && page.imagesCount > 0) {
      // Add sample image nodes if present
      xml += `    <!-- Google Image Sitemap Extension (${page.imagesCount} images detected) -->\n`;
      xml += '    <image:image>\n';
      xml += `      <image:loc>${escapeXml(page.url)}/og-image.jpg</image:loc>\n`;
      if (page.title) {
        xml += `      <image:title>${escapeXml(page.title)}</image:title>\n`;
      }
      xml += '    </image:image>\n';
    }

    xml += '  </url>\n';
  });

  xml += '</urlset>';
  return xml;
}

export function generateRobotsTxt(baseUrl = 'https://example.com', sitemapUrl) {
  const sitemap = sitemapUrl || `${baseUrl.replace(/\/$/, '')}/sitemap.xml`;
  return `# Robots.txt generated by SitemapFlow Pro
User-agent: *
Allow: /

# Exclude sensitive admin and private routes
Disallow: /admin/
Disallow: /api/
Disallow: /dashboard/private/

# Sitemap Location
Sitemap: ${sitemap}
`;
}

export function generateUrlListTxt(pages) {
  return pages.map(p => p.url).join('\n');
}

export function generateSeoCsv(pages) {
  const headers = ['URL', 'Status Code', 'Title', 'Title Length', 'Meta Description', 'Description Length', 'H1 Heading', 'Load Time (ms)', 'Depth', 'Has Canonical'];
  
  const rows = pages.map(p => [
    csvEscape(p.url),
    p.statusCode || 200,
    csvEscape(p.title || ''),
    (p.title || '').length,
    csvEscape(p.description || ''),
    (p.description || '').length,
    csvEscape(p.h1 || ''),
    p.loadTime || 0,
    p.depth || 0,
    p.hasCanonical ? 'Yes' : 'No'
  ]);

  return [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
}

function escapeXml(unsafe = '') {
  return String(unsafe)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function csvEscape(text = '') {
  const stringified = String(text).replace(/"/g, '""');
  return `"${stringified}"`;
}
